[package]
name = "backend-api"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "backend-api"
path = "src/main.rs"

[dependencies]
actix-web = { workspace = true }
actix-cors = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
config = { workspace = true }
dotenvy = { workspace = true }
uuid = { workspace = true }
domain = { workspace = true }
application = { workspace = true }
infrastructure = { workspace = true }
shared = { workspace = true }
chrono = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
parking_lot = { workspace = true }
futures-util = { workspace = true }
async-trait = { workspace = true }
csv = { workspace = true }
calamine = { workspace = true }
actix-multipart = { workspace = true }
rust_xlsxwriter = { workspace = true }
tempfile = { workspace = true }
